spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: 'create-drop'
    defer-datasource-initialization: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:db
    username: username
    password: password
    driverClassName: org.h2.Driver