spring:
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver