version: "3"

services:

  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"